# Generated by Django 5.2.8 on 2025-11-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
