# Generated by Django 5.2.8 on 2025-11-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
